---
- name: 'install nginx'
  apt:
    name: 'nginx={{ nginx_version }}-0ubuntu1'
    state: 'present'
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: 'upload nginx configs'
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/sites-available/default'
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'
    mode: 0644
  become: true
- name: 'check nginx is started'
  service: 'name=nginx state=started'
  become: true
